# Custom Server Teleport

# Add here the servers you want to access followed by the custom commands
servers:
    #- example:
    #    commands: ["example","ex"]
    #    permission: "customcommand.example"
    #    send_message: "<aqua>Sending <green>%playername%</green> to </aqua><green>%servername%</green>"
    - hub:
        commands: ["hub","lobby","l"]
        permission: "customcommand.hub"
        send_message: "" # Leave empty to disable the message