# Custom Server Teleport

# Add here the servers you want to access followed by the custom commands
servers:
    #- example:
    #    commands: ["example","ex"]
    #    permission: "customcommand.example"
    - hub:
        commands: ["hub","lobby","l"]
        permission: "customcommand.hub"